[alias]
  co = "checkout"
  nb = "switch -c"

  st = "status"
  
  cm = "commit -s -m"
  ce = "commit -s -e"
  ca = "commit -s --amend"
  
  ls = "branch -l"
  
  rr = "restore --staged --worktree"

  hh = "rev-parse HEAD"
  sh = "rev-parse --short HEAD"

  hh-clip = "!git rev-parse HEAD | wl-copy -n"
  sh-clip = "!git rev-parse --short HEAD | wl-copy -n"

  gg = "grep -E --line-number"

  psf = "push --force"

  # fat fingers...
  puhs = "push"

  dc = "diff --check"

  cleanall = "clean -fdx"

  delete-remote = "!git branch -vv | grep ': gone]' | grep -vE '\\*|\\+' | awk '{ print $1; }' | xargs -r git branch -D"

  # set upstream
  su = "!git branch -u $1/$2 $2 #"

  suir = "submodule update --init --recursive"

  # list files ignored by gitignore
  ignored = "ls-files -i -c --exclude-per-directory=.gitignore"

  # list aliases
  alias = "!git config --get-regexp ^alias\\. | sed -e s/^alias\\.// -e s/\\ /\\ =\\ / #"
