nnoremap <SPACE> <Nop>
let g:mapleader = " "
set listchars = "tab:» ","trail:·","nbsp=␣"
set autochdir
set hlsearch
set noshowmode
colorscheme nord

set rnu
set expandtab
set ignorecase
set mouse="a"
set shiftwidth=2
set smartcase
set tabstop=2

set undodir="tmp"
set undofile

set grepprg=rg\ --vimgrep\ --smart-case\ --follow
let g:airline_theme = "nord"
let g:move_key_modifier_visualmode = 'C'
let g:airline_powerline_fonts = 1
let g:NERDTreeHijackNetrw = 0
let g:lf_replace_netrw = 1
if has("termguicolors")
  set termguicolors
  if &t_8f == ''
    " The first characters after the equals sign are literal escape characters.
    set t_8f=[38;2;%lu;%lu;%lum
    set t_8b=[48;2;%lu;%lu;%lum
  endif
endif

so ~/vimcfgs/language-servers.vim

map <C-b> :Buffers<CR>
map <C-p> :Files<CR>
map <Leader>b :NERDTreeToggle<CR>
map <Leader><S-f> gg=G
